import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Dummy Products Shop",
  description: "Generated by create next app",
  icons: {
    icon: 'favicon/favicon-32x32.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
      </head>
      <body>{children}</body>
    </html>
  );
}
